In [2]:
from pixiedust_peacetech.dashBoard import *
import json

nlu = json.load(open('nlu.cred'))
natural_language_understanding = NaturalLanguageUnderstandingV1(
    version=nlu['version'],
    username=nlu['username'],
    password=nlu['password'])

headers=json.load(open('datahub.cred'))
PixieAppBoard().run(runInDialog='true')